### ISSUE TITLE
Reduce the number of transitive dependencies in laboratory-servlet-api-integration

### ISSUE THREAD

**Issue by tkvangorder** [wix/petri#12]
We are evaluating using petri in our environment and one issue we have run into is the number of transitive dependencies that are included in both the compile and runtime classpath when adding "laboratory-servlet-api-integration" to our projects. 

I was able to prune these down some with exclusions (I'm using gradle) 
 
compile("com.wixpress.common:laboratory-servlet-api-integration:1.19.0-SNAPSHOT") {
  exclude group: 'org.eclipse.jetty'
  exclude module: 'petri-test-utils'		
}

I am hoping for some help to identify which other transitive dependencies may be excluded from the client libraries. 

Thanks in advance for any help!

For reference, here is the dependency graph spit out by gradle: 

\--- com.wixpress.common:laboratory-servlet-api-integration:1.19.0-SNAPSHOT
     +--- commons-configuration:commons-configuration:1.10
     |    +--- commons-lang:commons-lang:2.6
     |    \--- commons-logging:commons-logging:1.1.1 -> 1.1.3
     +--- com.wixpress.common:wix-petri-core:1.19.0-SNAPSHOT
     |    +--- org.scala-lang:scala-library:2.11.6
     |    +--- org.reflections:reflections-maven:0.9.9-RC1
     |    |    +--- org.reflections:reflections:0.9.9-RC1
     |    |    |    +--- com.google.guava:guava:11.0.2 -> 17.0
     |    |    |    +--- org.javassist:javassist:3.16.1-GA
     |    |    |    \--- dom4j:dom4j:1.6.1
     |    |    |         \--- xml-apis:xml-apis:1.0.b2
     |    |    +--- org.jfrog.maven.annomojo:maven-plugin-anno:1.4.1
     |    |    \--- org.jfrog.jade.plugins.common:jade-plugin-common:1.3.8
     |    |         +--- org.jfrog.maven.annomojo:maven-plugin-anno:1.3.0 -> 1.4.1
     |    |         +--- ant:ant:1.6.5
     |    |         +--- org.apache.maven:maven-plugin-api:2.0.5
     |    |         +--- org.apache.maven:maven-project:2.0.5
     |    |         |    +--- org.apache.maven:maven-settings:2.0.5
     |    |         |    |    +--- org.apache.maven:maven-model:2.0.5
     |    |         |    |    |    \--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9
     |    |         |    |         +--- junit:junit:3.8.1
     |    |         |    |         +--- org.codehaus.plexus:plexus-utils:1.0.4 -> 1.1
     |    |         |    |         \--- classworlds:classworlds:1.1-alpha-2
     |    |         |    +--- org.apache.maven:maven-profile:2.0.5
     |    |         |    |    +--- org.apache.maven:maven-model:2.0.5 (*)
     |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9 (*)
     |    |         |    +--- org.apache.maven:maven-model:2.0.5 (*)
     |    |         |    +--- org.apache.maven:maven-artifact-manager:2.0.5
     |    |         |    |    +--- org.apache.maven:maven-repository-metadata:2.0.5
     |    |         |    |    |    \--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    +--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    +--- org.apache.maven:maven-artifact:2.0.5
     |    |         |    |    |    \--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    |    +--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9 (*)
     |    |         |    |    \--- org.apache.maven.wagon:wagon-provider-api:1.0-beta-2
     |    |         |    |         \--- org.codehaus.plexus:plexus-utils:1.0.4 -> 1.1
     |    |         |    +--- org.codehaus.plexus:plexus-utils:1.1
     |    |         |    +--- org.apache.maven:maven-artifact:2.0.5 (*)
     |    |         |    \--- org.codehaus.plexus:plexus-container-default:1.0-alpha-9 (*)
     |    |         +--- org.apache.maven:maven-artifact:2.0.5 (*)
     |    |         +--- org.apache.maven:maven-model:2.0.5 (*)
     |    |         +--- org.codehaus.plexus:plexus-utils:1.1
     |    |         +--- xstream:xstream:1.1.3
     |    |         \--- xpp3:xpp3:1.1.3.4-RC8
     |    +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     |    +--- org.springframework:spring-web:4.1.1.RELEASE (*)
     |    +--- org.springframework:spring-jdbc:4.1.1.RELEASE
     |    |    +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     |    |    +--- org.springframework:spring-core:4.1.1.RELEASE (*)
     |    |    \--- org.springframework:spring-tx:4.1.1.RELEASE
     |    |         +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     |    |         \--- org.springframework:spring-core:4.1.1.RELEASE (*)
     |    +--- org.apache.commons:commons-lang3:3.0.1
     |    +--- joda-time:joda-time:2.5
     |    +--- ch.qos.logback:logback-classic:1.0.6 -> 1.1.2 (*)
     |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     |    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.0 -> 2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-core:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     |    |    \--- joda-time:joda-time:2.2 -> 2.5
     |    +--- com.fasterxml.jackson.module:jackson-module-scala_2.11:2.4.3
     |    |    +--- org.scala-lang:scala-library:2.11.2 -> 2.11.6
     |    |    +--- org.scala-lang:scala-reflect:2.11.2
     |    |    |    \--- org.scala-lang:scala-library:2.11.2 -> 2.11.6
     |    |    +--- com.fasterxml.jackson.core:jackson-core:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     |    |    +--- com.thoughtworks.paranamer:paranamer:2.6
     |    |    +--- com.google.code.findbugs:jsr305:2.0.1
     |    |    \--- com.google.guava:guava:15.0 -> 17.0
     |    +--- com.google.guava:guava:17.0
     |    \--- javax.mail:mail:1.4.1
     |         \--- javax.activation:activation:1.1
     +--- com.wixpress.common:petri-server-core:1.19.0-SNAPSHOT
     |    +--- com.wixpress.common:wix-petri-core:1.19.0-SNAPSHOT (*)
     |    +--- org.springframework:spring-core:4.1.1.RELEASE (*)
     |    +--- org.springframework:spring-context:4.1.1.RELEASE (*)
     |    +--- org.springframework:spring-context-support:4.1.1.RELEASE
     |    |    +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     |    |    +--- org.springframework:spring-context:4.1.1.RELEASE (*)
     |    |    \--- org.springframework:spring-core:4.1.1.RELEASE (*)
     |    +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     |    \--- com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1
     |         \--- com.fasterxml.jackson.core:jackson-databind:2.0.2 -> 2.4.3 (*)
     +--- commons-pool:commons-pool:1.5.6
     +--- commons-dbcp:commons-dbcp:1.4
     |    \--- commons-pool:commons-pool:1.5.4 -> 1.5.6
     +--- com.h2database:h2:1.4.181
     +--- com.wixpress.common:petri-test-utils:1.19.0-SNAPSHOT
     |    +--- com.wixpress.common:wix-petri-core:1.19.0-SNAPSHOT (*)
     |    +--- commons-configuration:commons-configuration:1.10 (*)
     |    +--- org.apache.httpcomponents:httpclient:4.3.1
     |    |    +--- org.apache.httpcomponents:httpcore:4.3
     |    |    +--- commons-logging:commons-logging:1.1.3
     |    |    \--- commons-codec:commons-codec:1.6
     |    +--- com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1 (*)
     |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     |    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.4.3 (*)
     |    +--- com.fasterxml.jackson.module:jackson-module-scala_2.10:2.4.3
     |    |    +--- org.scala-lang:scala-library:2.10.4 -> 2.11.6
     |    |    +--- org.scala-lang:scala-reflect:2.10.4 -> 2.11.2 (*)
     |    |    +--- com.fasterxml.jackson.core:jackson-core:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.3
     |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     |    |    +--- com.thoughtworks.paranamer:paranamer:2.6
     |    |    +--- com.google.code.findbugs:jsr305:2.0.1
     |    |    \--- com.google.guava:guava:15.0 -> 17.0
     |    +--- mysql:mysql-connector-mxj:5.0.12
     |    |    +--- mysql:mysql-connector-mxj-db-files:5.0.12
     |    |    \--- mysql:mysql-connector-java:5.1.17
     |    +--- commons-io:commons-io:2.4
     |    +--- org.slf4j:slf4j-simple:1.7.7
     |    |    \--- org.slf4j:slf4j-api:1.7.7
     |    \--- org.springframework:spring-jdbc:4.1.1.RELEASE (*)
     +--- org.springframework:spring-core:4.1.1.RELEASE (*)
     +--- org.springframework:spring-context:4.1.1.RELEASE (*)
     +--- org.springframework:spring-context-support:4.1.1.RELEASE (*)
     +--- org.springframework:spring-beans:4.1.1.RELEASE (*)
     +--- org.springframework:spring-web:4.1.1.RELEASE (*)
     +--- org.springframework:spring-webmvc:4.1.1.RELEASE (*)
     +--- com.github.briandilley.jsonrpc4j:jsonrpc4j:1.1 (*)
     +--- com.fasterxml.jackson.core:jackson-databind:2.4.3 (*)
     +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.4.3 (*)
     \--- com.fasterxml.jackson.module:jackson-module-scala_2.10:2.4.3 (*)

**Comment by talya** [comment]
Hi,

I've done some cleanups, got rid of several old dependencies etc.
Also you could filter out everything with maven in it.

The list should be much smaller now.

Let us know how it goes!
